### ISSUE TITLE
Two of the unit tests are failing.

### ISSUE THREAD

**Issue by wforney** [bbowyersmyth/SpellCheck#3]
When I pulled the repo and ran the tests two of them failed. After updating for my PR they are still failing. I didn't have time to look into that.

**Comment by bbowyersmyth** [comment]
The tests depend on Windows environment configuration. For example MultiSessionTest requires en-us and fr-fr languages be installed.
Which ones failed for you?

**Comment by wforney** [comment]
Ok, that explains the issue as I don't have anything except en-us installed on my dev box. I'll add fr-fr and try it again. It was the LanguageIdTest and MultisessionTest that were failing and I see that they both may need other locales installed to work properly.

**Comment by wforney** [comment]
After installing fr-fr and en-au I see the LanguageIdTest passed. I had to modify the expected number of suggestions returned in the other one to 10 from 4 because it was returning more suggestions than expected. If that is not correct behavior, please let me know.
