### ISSUE TITLE
Error: Class is not licensed for use

### ISSUE THREAD

**Issue by LaraSQP** [bbowyersmyth/SpellCheck#6]
First of all, thank you for putting the time into this project and making it available.

The error:

 'System.Runtime.InteropServices.COMException (0x80040112): Creating an instance of the COM component with CLSID {7AB36653-1796-484B-BDFA-E74F1DB7C1DC} from the IClassFactory failed due to the following error: 80040112 Class is not licensed for use (Exception from HRESULT: 0x80040112).

   at PlatformSpellCheck.SpellChecker..ctor(String languageTag)

Any ideas?

**Comment by bbowyersmyth** [comment]
Hi, Is this running on .net core or framework? Which version?
Also what version of Windows?

**Comment by LaraSQP** [comment]
Thanks for the quick reply.

Windows 10.

I have tried both framework and standard.

I have even cloned your repo and compiled the library myself. Same error. I think there is something screwed up in my dev machine (GAC?) and the issue is unrelated to your code.

If something occurs to you, it would be most welcome. But consider the issue closed otherwise.
